gdip_admin:
    resource: "@GDIPAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

gdip_user:
    resource: "@GDIPUserBundle/Controller/"
    type:     annotation
    prefix:   /GDIP/

gdipgdip:
    resource: "@GDIPGDIPBundle/Controller/"
    type:     annotation
    prefix:   /GDIP/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"