security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADHERENT:    ROLE_USER
        ROLE_ADMIN:       ROLE_ADHERENT
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                login_path: fos_user_security_login
                use_forward: false
                check_path: fos_user_security_check
                failure_path: null
                default_target_path: index
                remember_me: true
            remember_me:
                key: %secret%
                lifetime: 300000000
                path: /
                domain: ~
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/GDIP, role: ROLE_USER }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/GDIP/admin/, role: ROLE_ADMIN }
