<?php

namespace GDIP\GDIPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PossederRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PossederRepository extends EntityRepository
{
}
