<?php

namespace GDIP\GDIPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PosteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosteRepository extends EntityRepository
{
}
