<?php

namespace GDIP\GDIPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PreChoixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreChoixRepository extends EntityRepository
{
	public function getPreChoixByPosition($userId, $position)
	{
		$query = $this->createQueryBuilder('p')
            ->where("p.utilisateur = :user")
            ->andWhere("p.position = :position")
            ->andWhere("p.traite = false")
            ->setParameter("user", $userId)
            ->setParameter("position", $position);

        return $query->getQuery()->getSingleResult();
	}

	public function setAllPreChoixTraiteNull($em)
	{
		$entities = $this->findAll();

        foreach ($entities as $preChoix) {
            $preChoix->setTraite(false);
            $em->persist($preChoix);
            $em->flush();
        }
	}

	public function setPositionPreChoix($em, $preChoix, $position)
	{
		$preChoix->setPosition($position);
        $preChoix->setTraite(true);
        $em->persist($preChoix);
        $em->flush();
	}
}
